export enum TooltipChartType {
  RADAR = "RADAR",
  BAR_CHART = "BAR_CHART",
  MIXED_BAR_LINE_CHART = "MIXED_BAR_LINE_CHART",
  DETAILS_BAR_CHART = "DETAILS_BAR_CHART",
  LINE_CHART = "LINE_CHART",
  DOUGHNUT = "DOUGHNUT",
}
